### ISSUE TITLE
rowdy.begin is not a function error

### ISSUE THREAD

**Issue by EvaB85** [Hoten/rowdy#1]
Using rowdy logger version 1.0.0 and Express version 4.16.3 when I run npm start I get the error: 

`
/Users/username/coding/ga-projects/fitness-trails/server.js:19
rowdy.begin(app);
      ^

TypeError: rowdy.begin is not a function
    at Object.<anonymous> (/Users/username/coding/ga-projects/fitness-trails/server.js:19:7)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[nodemon] app crashed - waiting for file changes before starting...
`

I followed your doc and added the require and the other lines yet when I downgraded to rowdy-logger 0.0.2 everything worked. I am not sure if I did something wrong.

Thanks,

Eva

**Comment by Hoten** [comment]
Hi Eva, can you provide the first 18 line of `server.js`

Also, in GH, you can wrap code in triple backticks (` ` `, no spaces), and it will be stylized:
```
like this
```

**Comment by connorjclark** [comment]
v1.0.2 fixes this - if you update, you can just do `var rowdy = require('rowdy-logger')` like the doc says.

**Comment by EvaB85** [comment]
Hi Connor,

I did not see your emails until now. I’ve been sick all week and now catching up on emails. Thank you for the information. I got it to work. I really appreciate it.

-Eva
